#!/bin/bash

echo "🚨 紧急启用GitHub Pages！"
echo "=================="
echo ""
echo "❌ 当前状态：GitHub Pages未启用"
echo "✅ 解决方案：立即手动启用"
echo ""
echo "📋 请按以下步骤操作："
echo ""
echo "1️⃣ 打开浏览器访问："
echo "   https://github.com/luciano-007/007/settings/pages"
echo ""
echo "2️⃣ 在页面中设置："
echo "   • Source: Deploy from a branch"
echo "   • Branch: main"
echo "   • Folder: / (root)"
echo "   • 点击 Save"
echo ""
echo "3️⃣ 等待部署完成："
echo "   • 访问：https://github.com/luciano-007/007/actions"
echo "   • 等待绿色✅标志出现"
echo ""
echo "4️⃣ 最终访问地址："
echo "   https://luciano-007.github.io/007"
echo ""
echo "⏱️ 整个过程需要2-3分钟"
echo ""
echo "完成后访问：https://luciano-007.github.io/007 查看你的网站！"